version: '3'

volumes:
  postgres_volume:
  redis_volume:

services:
  pg:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  redis:
    image: redis
    environment:
      - "REDIS_PORT=${REDIS_PORT}"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_volume:/var/lib/redis/data